/**
 * Application Error Codes
 */
export const ERROR_CODES = {
  // General Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Resource Errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Database Errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',

  // Business Logic Errors
  ENROLLMENT_ALREADY_EXISTS: 'ENROLLMENT_ALREADY_EXISTS',
  MODULE_NOT_COMPLETED: 'MODULE_NOT_COMPLETED',
  ASSIGNMENT_ALREADY_SUBMITTED: 'ASSIGNMENT_ALREADY_SUBMITTED',
  QUIZ_ALREADY_ATTEMPTED: 'QUIZ_ALREADY_ATTEMPTED',
  INVALID_QUIZ_ANSWER: 'INVALID_QUIZ_ANSWER',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // External Service Errors
  CACHE_ERROR: 'CACHE_ERROR',
  QUEUE_ERROR: 'QUEUE_ERROR',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
